name: cat_trivia
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-56.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  equatable: ^2.0.5
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  get_it: ^7.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  auto_route: ^6.4.0
  dio: ^5.1.1
  intl: ^0.18.1
  flutter_advanced_networkimage_2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: ^2.4.1
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  auto_route_generator: ^6.2.0

flutter:
  uses-material-design: true